---
services:
  kali:
    image: ryaben/kali-dtunetsec:latest
    platform: linux/amd64
    ports:
      - "127.0.0.1:6901:6901"
    environment:
      VNC_PW: "password"
    cap_add:
      - NET_ADMIN
      - NET_RAW

  defender:
    image: ryaben/defender-dtunetsec:latest
    platform: linux/amd64
    profiles: [threat-detection, authentication, blue-team, privacy]
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  iot:
    image: ryaben/iot-dtunetsec:latest
    platform: linux/amd64
    profiles: [iot]

  cowrie:
    image: cowrie/cowrie
    profiles: [threat-detection]

  # Used for the "11 - Red team" lab
  juice-shop:
    image: bkimminich/juice-shop
    profiles: [red-team]
    ports:
      - "127.0.0.1:3000:3000"